name: Build to build branch
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境
    steps:
      - name: Checkout codes 🛎
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # 设置 node 运行环境
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      # 设置缓存依赖，加快下次安装依赖的速度
      - name: Cache node modules
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build


      - name: Transfer to build branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: dist

